version: '3.8'
services:
  api:
    build:
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/order_management?schema=public
    command: 'sh post-up.sh'

  postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=order_management
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
